In [1]:
import numpy as np
import pandas as pd

In [2]:
s = pd.Series([1,2,3,np.nan, 8,9])
s

0    1.0
1    2.0
2    3.0
3    NaN
4    8.0
5    9.0
dtype: float64

In [3]:
lista = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
]

In [4]:
a = pd.DataFrame(lista)
a

    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [5]:
a = {"a": 10, "b": 20}
b = pd.Series(a)
b

a    10
b    20
dtype: int64

In [6]:
s = pd.Series(5, index=['fila1', 'fila2'])
s

fila1    5
fila2    5
dtype: int64

In [7]:
a = pd.DataFrame({'col1':{'fila1':1,'fila2':2}, 'col2':{'fila1':3,'fila2':4}})
a

       col1  col2
fila1     1     3
fila2     2     4

In [8]:
dates = pd.date_range("20130101", periods=6)

 
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01  0.801870  1.053956 -0.022401  0.267127
2013-01-02  1.053415 -0.763657  0.864788 -1.079472
2013-01-03 -0.031293  0.420130  0.685311 -1.402146
2013-01-04  1.693570 -0.716178  2.127717  0.237074
2013-01-05  0.690211 -0.008458  0.972370 -0.592045
2013-01-06 -0.180525  0.980838 -0.817335 -0.656253

In [9]:
a = pd.Categorical(["malo","bueno", "regular", "bueno"])


len(a.categories)

3

In [10]:
a =[2,3,4,5]
# n = np.array([3] * 4)
n = np.array(a)
print(n)

[2 3 4 5]

In [11]:
lista = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
]

idx = pd.Index(list("ABCD"))
df = pd.DataFrame(lista, index=idx)
#columns=list("ABC"))
# df.sort_index(axis=1, ascending=False)


df[df < 3]

     0    1   2
A  1.0  2.0 NaN
B  NaN  NaN NaN
C  NaN  NaN NaN
D  NaN  NaN NaN

In [12]:
df = pd.DataFrame(
     [[1, 2], [4, 5], [7, 8]],
     index=["cobra", "viper", "sidewinder"],
     columns=["max_speed", "shield"],
)

df

            max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8

In [13]:
df[['max_speed','shield']] < 3

            max_speed  shield
cobra            True    True
viper           False   False
sidewinder      False   False

In [23]:
f = pd.DataFrame({
    'Nombre': ['Ana', 'Carlos', 'Luis', 'María'],
    'Ciudad': ['Madrid', 'Barcelona', 'Madrid', 'Sevilla'],
    'Compras': [100, 250, 50, 400]
})
df

   Nombre     Ciudad  Compras
0     Ana     Madrid      100
1  Carlos  Barcelona      250
2    Luis     Madrid       50
3   María    Sevilla      400

In [26]:
df = pd.DataFrame({
    'Nombre': ['Ana', 'Carlos', 'Luis', 'María'],
    'Ciudad': ['Madrid', 'Barcelona', 'Madrid', 'Sevilla'],
    'Compras': [100, 250, 50, 400]
})
mascara = (df['Ciudad'] == 'Madrid') & (df['Compras'] > 90)
type(df)

pandas.DataFrame

In [32]:
df = pd.read_csv("test")
df.head()

IsADirectoryError: [Errno 21] Is a directory: 'test'